root:
  title: "Project items"
  children: models, data, sops, presentations, publications
  deletable: false

models:
  title: "Models"
  children: sbml

sbml:
  title: "SBML"
  children: published

published:
  title: "Published"

data:
  title: "Data Files"

sops:
  title: "SOPs"

presentations:
  title: "Presentations"

publications:
  title: "Publications"

unsorted_items:
  title: "Unsorted items"
  editable: false
  deletable: false
  incoming: true