models:
  title: "Models"
  children: sbml

sbml:
  title: "SBML"
  children: published

published:
  title: "Published"


data:
  title: "Data Files"

sops:
  title: "SOPs"

presentations:
  title: "Presentations"

unsorted_items:
  title: "Unsorted items"
  editable: false
  incoming: true