hits:
  id: 1
  name: HITS gGmbH
  address: Schloss-Wolfsbrunnenweg 35
  web_page: http://www.h-its.org
  city: Heidelberg
  country: Germany
  
medma:
  id: 2
  name: Medical Faculty Mannheim 
  address: Theodor Kutzer Ufer 1-3
  web_page: 
  city: Mannheim
  country: Germany

dhzb:
  id: 3
  name: Pathologie des Deutschen Herzzentrums
  address: Augustenburger Platz 1
  web_page: 
  city: Berlin
  country: Germany

