concentration:
  title: concentration

pressure:
  title: pressure

PH:
  title: acidity/PH

specific concentration:
  title: specific concentration

stiring rate:
  title: stiring rate

temperature:
  title: temperature

time:
  title: time

glucose pulse:
  title: glucose pulse

dilution rate:
  title: dilution rate

gas flow rate:
  title: gas flow rate

dry biomass concentration:
  title: dry biomass concentration

optical density 600 nm:
  title: optical density 600 nm

