ODE:
  title: Ordinary differential equations

linear equations:
  title: Linear equations

algebraic equations:
  title: Algebraic equations

partial differential equations:
  title: Partial differential equations