Bacillus subtilis:
  title: Bacillus subtilis
  
Bos taurus:
  title: Bos taurus

Homo sapiens:
  title: Homo sapiens

Mus musculus:
  title: Mus musculus

Oryctolagus cuniculus:
  title: Oryctolagus cuniculus

Ovis aries:
  title: Ovis aries

Rattus norvegicus:
  title: Rattus norvegicus

Sus scrofa:
  title: Sus scrofa



Trypanosoma brucei:
  title: Trypanosoma brucei

Lactobacillus plantarum:
  title: Lactobacillus plantarum