test_data:
  id: 1
  title: Test data
  description: Data used for model testing

validation_data:
  id: 2
  title: Validation data
  description: Data used for validating a model

produced_data:
  id: 3
  title: Produced data
  description: Data produced by a model
