WP coordinator:
  id: 1
  name: Workpackage Coordinator

project coordinator:
  id: 2
  name: Project Coordinator

project vice coordinator:
  id: 3
  name: Project Vice Coordinator

PI:
  id: 4
  name: Principal Investigator

research associate:
  id: 5
  name: Research Associate

postdoc:
  id: 6
  name: Postdoc

PhD student:
  id: 7
  name: Student

pal:
  id: 8
  name: Virtual Liver Pal


