K-12/MG1655 (wild-type/wild-type):
  id: 1
  contributor_id: 132

MC4100 (wild-type/wild-type):
  id: 2
  contributor_id:

168 (wild-type/wild-type):
  id: 3
  contributor_id: 114

NCIB3610 (wild-type/wild-type):
  id: 4
  contributor_id: 250

JW49 (wild-type/wild-type):
  id: 5
  contributor_id:

ATCC6633 (wild-type/wild-type):
  id: 6
  contributor_id:

V583 (wild-type/wild-type):
  id: 7
  contributor_id: 13

ATCC29200 (wild-type/wild-type):
  id: 8
  contributor_id:

DS5 (wild-type/wild-type):
  id: 9
  contributor_id:

TX0012 (wild-type/wild-type):
  id: 10
  contributor_id:

M49 (591) (wild-type/wild-type):
  id: 11
  contributor_id: 241

ATCC824 (wild-type/wild-type):
  id: 12
  contributor_id: 197

NCIMB8052 (wild-type/wild-type):
  id: 13
  contributor_id:

DOT-T1 (wild-type/wild-type):
  id: 14
  contributor_id: 150

NCIMB10525 (wild-type/wild-type):
  id: 15
  contributor_id:

A3(2) (wild-type/wild-type):
  id: 16
  contributor_id: 77

M145 (wild-type/wild-type):
  id: 17
  contributor_id: 77

P2 (wild-type/wild-type):
  id: 18
  contributor_id:

YJM789 (wild-type/wild-type):
  id: 19
  contributor_id:

FY2 diploid (wild-type/wild-type):
  id: 20
  contributor_id:

FY3 diploid (wild-type/wild-type):
  id: 21
  contributor_id:

YSBN1 diploid (wild-type/wild-type):
  id: 22
  contributor_id: 19

YSBN2 diploid (wild-type/wild-type):
  id: 23
  contributor_id: 19

CEN.PK113-7D haploid (wild-type/wild-type):
  id: 24
  contributor_id:

BY4741 (wild-type/wild-type):
  id: 25
  contributor_id: 42

BSG 112 (wild-type/wild-type):
  id: 26
  contributor_id: 114

168 trp+ (wild-type/wild-type):
  id: 27
  contributor_id: 114

L. lactis (wild-type/wild-type):
  id: 28
  contributor_id:

D39 (wild-type/wild-type):
  id: 32
  contributor_id: 250

Tbrucei427 (wild-type/wild-type):
  id: 33
  contributor_id:

WCFS1 (wild-type/wild-type):
  id: 34
  contributor_id:

2T1 (wild-type/wild-type):
  id: 38
  contributor_id: 215
