technology:
  title: technology
  children: genomics_technologies,metabolomics_technology,proteomics_technologies,transcriptomics_technologies

genomics_technologies:
  title: genomics technologies
  children: qPRC

qPCR:
  title: qPCR

#----------------------------------------------------

metabolomics_technology:
  title: metabolomics technologies
  children: chemostat,gas_chromatography,HPLC,Mass_Spectormetry,UPLC

chemostat:
  title: chemostat

gas_chromatography:
  title: gas chromatography

HPLC:
  title: HPLC

Mass_Spectormetry:
  title: Mass Spectrometry
  children: liquid_chromatography-tandem_mass_spectrometry

liquid_chromatography-tandem_mass_spectrometry:
  title: liquid chromatography-tandem mass spectrometry

UPLC:
  title: UPLC

#----------------------------------------------------

proteomics_technologies:
  title: proteomics technologies
  children: 2-hybrid_system,2D_gel_electrophoresis,NMR,surface_plasmon_resonance,HPLC,Mass_Spectormetry

2-hybrid_system:
  title: 2-hybrid system

2D_gel_electrophoresis:
  title: 2D gel electrophoresis

NMR:
  title: NMR

surface_plasmon_resonance:
  title: surface plasmon resonance


#----------------------------------------------------

transcriptomics_technologies:
  title: transcriptomics technologies
  children: microarray,qRT-PCR

microarray:
  title: microarray
  children: cDNA_microarray,ChIP-on-chip,custom_Array,DNA_Methylation,miRNA_microarray

cDNA_microarray:
  title: cDNA microarray

ChIP-on-chip:
  title: ChIP-on-chip

custom_Array:
  title: custom Array

DNA_Methylation:
  title: DNA Methylation

miRNA_microarray:
  title: miRNA microarray

qRT-PCR:
  title: qRT-PCR