seconds:
  symbol: s
  comment: time

minutes:
  symbol: min
  comment: time

hour:
  symbol: h
  comment: time

hour-1:
  symbol: h-1
  comment: rate

min-1:
  symbol: min-1
  comment: rate

litre:
  symbol: L
  comment: volume

metre:
  symbol: m
  comment: length

gram:
  symbol: g
  comment: mass

celcius:
  symbol: °C
  comment: temperature

mol:
  symbol: mol
  comment: amount of substance

M:
  symbol: M
  comment: concentration per litre of corresponding comparment

mM:
  symbol: mM
  comment: concentration per litre of corresponding comparment

muM:
  symbol: µM
  comment: concentration per litre of corresponding comparment

pM:
  symbol: pM
  comment: concentration per litre of corresponding comparment

grams_per_litre:
  symbol: g/L
  comment: concentration per litre of corresponding comparment

g/g_DW:
  symbol: g/g_DW
  comment: specific concentration per gram of dry weigh biomass

mg/g_DW:
  symbol: mg/g_DW
  comment: specific concentration per gram of dry weigh biomass

muMol-g_DW:
  symbol: muMol/g_DW
  comment: specific concentration per gram of dry weigh biomass

mmol/g_DW:
  symbol: mmol/g_DW
  comment: specific concentration per gram of dry weigh biomass

µmol/L_CV:
  symbol: µmol/L_CV
  comment: specific concentration per litre of cytoplasmic volume

mmol/L_CV:
  symbol: mmol/L_CV
  comment: specific concentration per litre of cytoplasmic volume

µmol/(g_DW*min):
  symbol: µmol/(g_DW*min)
  comment: specific rate per gram of dry weigh biomass

µm:
  symbol: µm
  comment: cellular size (diameter)

a.u.:
  symbol: a.u.
  comment: arbitrary units

±SD:
  symbol: ±SD
  comment: standard deviation

percent:
  symbol: %
  comment: percentage

acidity:
  symbol: pH
  comment: pH


