dimensionless:
  symbol: dimensionless
  comment: dimensionless

seconds:
  symbol: s
  comment: time

minutes:
  symbol: min
  comment: time

hour:
  symbol: h
  comment: time

hour-1:
  symbol: h-1
  comment: rate
  factors_studied: false

min-1:
  symbol: min-1
  comment: rate
  factors_studied: false

sec-1:
  symbol: sec-1
  comment: rate
  factors_studied: false

litre:
  symbol: L
  comment: litre

millilitre:
  symbol: mL
  comment: millilitre

microlitre:
  symbol: µL
  comment: microlitre

bar:
  symbol: bar
  comment: headspace pressure

rpm:
  symbol: rpm
  comment: revolutions per minute

L/min:
  symbol: L/min
  comment: flow rate

mL/min:
  symbol: mL/min
  comment: flow rate

metre:
  symbol: m
  comment: metre
  factors_studied: false

gram:
  symbol: g
  comment: gram

miligram:
  symbol: mg
  comment: milligram

microgram:
  symbol: µg
  comment: microgram

mpicogram:
  symbol: pg
  comment: mpicogram

celcius:
  symbol: °C
  comment: Celcius

mol:
  symbol: mol
  comment: amount of substance

M:
  symbol: M
  comment: concentration per litre of corresponding comparment

mM:
  symbol: mM
  comment: concentration per litre of corresponding comparment

muM:
  symbol: µM
  comment: concentration per litre of corresponding comparment

pM:
  symbol: pM
  comment: concentration per litre of corresponding comparment

grams_per_litre:
  symbol: g/L
  comment: concentration per litre of corresponding comparment

g/g_DW:
  symbol: g/g_DW
  comment: specific concentration per gram of dry weigh biomass
  factors_studied: false

mg/g_DW:
  symbol: mg/g_DW
  comment: specific concentration per gram of dry weigh biomass
  factors_studied: false

muMol-g_DW:
  symbol: muMol/g_DW
  comment: specific concentration per gram of dry weigh biomass
  factors_studied: false

mmol/g_DW:
  symbol: mmol/g_DW
  comment: specific concentration per gram of dry weigh biomass
  factors_studied: false

µmol/L_CV:
  symbol: µmol/L_CV
  comment: specific concentration per litre of cytoplasmic volume
  factors_studied: false

mmol/L_CV:
  symbol: mmol/L_CV
  comment: specific concentration per litre of cytoplasmic volume
  factors_studied: false

µmol/(g_DW*min):
  symbol: µmol/(g_DW*min)
  comment: specific rate per gram of dry weigh biomass
  factors_studied: false

µm:
  symbol: µm
  comment: micrometer

a.u.:
  symbol: a.u.
  comment: arbitrary units

percent:
  symbol: %
  comment: percentage

