people:
  index: latest
projects:
  index: latest
institutions:
  index: latest
investigations:
  index: latest
studies:
  index: latest
assays:
  index: latest
data_files:
  index: latest
models:
  index: latest
sops:
  index: latest
publications:
  index: latest
events:
  index: latest