
--- 
db_files: 
  columns: 
  - id
  - data
  records: 
  - - "5"
    - !binary |
      yv66vgAAADIAMQoADAAVCgAWABcJABgAGQcAGgoABAAVCAAbCgAEABwKAAQA
      HQoABAAeCgAfACAHACEHACIBAAY8aW5pdD4BAAMoKVYBAARDb2RlAQAPTGlu
      ZU51bWJlclRhYmxlAQAEbWFpbgEAFihbTGphdmEvbGFuZy9TdHJpbmc7KVYB
      AApTb3VyY2VGaWxlAQAMQ29udmVydC5qYXZhDAANAA4HACMMACQAJQcAJgwA
      JwAoAQAXamF2YS9sYW5nL1N0cmluZ0J1aWxkZXIBABlUaGUgY29udmVydGVk
      IGN1cnJlbmN5IGlzDAApACoMACkAKwwALAAtBwAuDAAvADABAAdDb252ZXJ0
      AQAQamF2YS9sYW5nL09iamVjdAEAD2phdmEvbGFuZy9GbG9hdAEACnBhcnNl
      RmxvYXQBABUoTGphdmEvbGFuZy9TdHJpbmc7KUYBABBqYXZhL2xhbmcvU3lz
      dGVtAQADb3V0AQAVTGphdmEvaW8vUHJpbnRTdHJlYW07AQAGYXBwZW5kAQAt
      KExqYXZhL2xhbmcvU3RyaW5nOylMamF2YS9sYW5nL1N0cmluZ0J1aWxkZXI7
      AQAcKEYpTGphdmEvbGFuZy9TdHJpbmdCdWlsZGVyOwEACHRvU3RyaW5nAQAU
      KClMamF2YS9sYW5nL1N0cmluZzsBABNqYXZhL2lvL1ByaW50U3RyZWFtAQAH
      cHJpbnRsbgEAFShMamF2YS9sYW5nL1N0cmluZzspVgAhAAsADAAAAAAAAgAB
      AA0ADgABAA8AAAAdAAEAAQAAAAUqtwABsQAAAAEAEAAAAAYAAQAAAAEACQAR
      ABIAAQAPAAAATgAEAAMAAAAqKgMyuAACRCoEMrgAAkWyAAO7AARZtwAFEga2
      AAcjJGq2AAi2AAm2AAqxAAAAAQAQAAAAEgAEAAAAAwAHAAQADgAFACkABgAB
      ABMAAAACABQ=

