
--- 
help_attachments: 
  columns: 
  - id
  - help_document_id
  - title
  - content_type
  - filename
  - size
  - db_file_id
  - created_at
  - updated_at
  records: 
  - - "3"
    - "13"
    - Nature Protocols Format for SOPs
    - application/msword
    - NatureProtocolsFormat.doc
    - "24064"
    - "5"
    - 2010-09-08 13:11:19
    - 2010-09-08 13:11:19
  - - "4"
    - "13"
    - MIAME_metadata
    - application/vnd.ms-excel
    - microarray_example_newformat.xls
    - "102400"
    - "7"
    - 2010-11-02 13:43:31
    - 2010-11-02 13:43:31
  - - "5"
    - "13"
    - Intracellular metabolite mesurements
    - application/vnd.ms-excel
    - metabolites_intracellular.xls
    - "75776"
    - "8"
    - 2010-11-02 13:44:55
    - 2010-11-02 13:44:55
