
--- 
help_images: 
  columns: 
  - id
  - help_document_id
  - content_type
  - filename
  - size
  - height
  - width
  - parent_id
  - thumbnail
  - created_at
  - updated_at
  records: 
  - - "1"
    - "15"
    - image/png
    - ISAUpperLevel.png
    - "12910"
    - "210"
    - "718"
    - 
    - 
    - 2012-09-26 14:57:27
    - 2012-09-26 14:57:27
  - - "2"
    - 
    - image/png
    - ISAUpperLevel_thumb.png
    - "12910"
    - "19"
    - "64"
    - "1"
    - thumb
    - 2012-09-26 14:57:27
    - 2012-09-26 14:57:27
  - - "3"
    - "15"
    - image/png
    - ISADataModel.png
    - "19014"
    - "256"
    - "736"
    - 
    - 
    - 2012-09-26 14:57:59
    - 2012-09-26 14:57:59
  - - "4"
    - 
    - image/png
    - ISADataModel_thumb.png
    - "19014"
    - "22"
    - "64"
    - "3"
    - thumb
    - 2012-09-26 14:57:59
    - 2012-09-26 14:57:59
